------------------------------------------------------CREACIÓN DE LA BASE DE DATOS-----------------------------------------------------------
CREATE DATABASE PROYECTO3;
GO

-------------------------------------------------------USO DE LA BASE DE DATOS---------------------------------------------------------------
USE PROYECTO3;
GO

--------------------------------------------------------CREACIÓN DE LA TABLAS----------------------------------------------------------------
CREATE TABLE CLIENTES 
(
	CODIGO_CLIENTE INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	NOMBRE_CLIENTE VARCHAR(50) NOT NULL,
	FECHA_CREACION DATETIME NOT NULL,
	TELEFONO VARCHAR(10) NOT NULL,
	CREDITO_MAXIMO MONEY NOT NULL
);

CREATE TABLE AUD_CLIENTES 
(
	CODIGO_AUD INT IDENTITY(1,1) PRIMARY KEY,
	CODIGO_CLIENTE INT NOT NULL,
	NOMBRE_ANTES VARCHAR(50) NULL,
	FECHA_CREACION_ANTES DATETIME NULL,
	TELEFONO_ANTES VARCHAR(10) NULL,
	CREDITO_ANTES MONEY NULL,
	NOMBRE_DESPUES VARCHAR(50) NOT NULL,
	FECHA_CREACION_DESPUES DATETIME NOT NULL,
	TELEFONO_DESPUES VARCHAR(10) NOT NULL,
	CREDITO_DESPUES MONEY NOT NULL,
	MODIFICADO_POR VARCHAR(50) NOT NULL,
	FECHA DATETIME NOT NULL,
	TIPO_TRANSACCION VARCHAR(5) NOT NULL
);

----------------------------------------------------CREACIÓN DEL PROCEDIMIENTO INSERTAR-----------------------------------------------------
CREATE PROCEDURE SP_INSERTA_CLIENTE
@NOMBRE_CLIENTE VARCHAR(50),
@TELEFONO VARCHAR(10),
@CREDITO_MAXIMO MONEY

AS
	BEGIN
		
		INSERT INTO CLIENTES VALUES 
		(
			@NOMBRE_CLIENTE, 
			GETDATE(), 
			@TELEFONO, 
			@CREDITO_MAXIMO
		);
	END;

GO


----------------------------------------------------EJECUCIÓN DEL PROCEDIMIENTO INSERTAR---------------------------------------------------
EXECUTE SP_INSERTA_CLIENTE 'CARLOS GARITA', '71098984', 1000000;


----------------------------------------------------CREACIÓN DEL PROCEDIMIENTO ACTUALIZAR--------------------------------------------------
CREATE PROCEDURE SP_UPDATE_CLIENTE
@CODIGO_CLIENTE INT,
@NOMBRE_CLIENTE VARCHAR(50),
@TELEFONO VARCHAR(10),
@CREDITO_MAXIMO MONEY

AS
	BEGIN
		
		UPDATE CLIENTES 
		SET NOMBRE_CLIENTE = @NOMBRE_CLIENTE, 
			TELEFONO = @TELEFONO, 
			CREDITO_MAXIMO = @CREDITO_MAXIMO
		WHERE CODIGO_CLIENTE = @CODIGO_CLIENTE;
	END;

GO


-----------------------------------------------------EJECUCIÓN DEL PROCEDIMIENTO ACTUALIZAR-------------------------------------------------
EXECUTE SP_UPDATE_CLIENTE 3, 'NATALIA', '71098986', 2000000;


---------------------------------------------------CREACIÓN DEL TRIGGER POR INSERCIÓN DE DATOS----------------------------------------------
CREATE TRIGGER TR_INSERT_CLIENTE
ON CLIENTES
FOR INSERT
AS
	DECLARE @CODIGO_CLIENTE INT;
	DECLARE @NOMBRE_DESPUES VARCHAR(50);
	DECLARE @FECHA_CREACION_DESPUES DATETIME;
	DECLARE @TELEFONO_DESPUES VARCHAR(10);
	DECLARE @CREDITO_DESPUES MONEY;
	DECLARE @TIPO_TRANSACCION VARCHAR(5) = 'INS';

	SELECT @CODIGO_CLIENTE = CODIGO_CLIENTE FROM CLIENTES;
	SELECT @NOMBRE_DESPUES = NOMBRE_CLIENTE FROM CLIENTES;
	SELECT @FECHA_CREACION_DESPUES = FECHA_CREACION FROM CLIENTES;
	SELECT @TELEFONO_DESPUES = TELEFONO FROM CLIENTES;
	SELECT @CREDITO_DESPUES = CREDITO_MAXIMO FROM CLIENTES;

	INSERT INTO AUD_CLIENTES VALUES 
	(
		@CODIGO_CLIENTE,
		NULL, 
		NULL, 
		NULL, 
		NULL, 
		@NOMBRE_DESPUES, 
		@FECHA_CREACION_DESPUES, 
		@TELEFONO_DESPUES, 
		@CREDITO_DESPUES, 
		SYSTEM_USER, 
		GETDATE(), 
		@TIPO_TRANSACCION
	);

GO


--------------------------------------------------CREACIÓN DEL TRIGGER POR ACTUALIZACIÓN DE DATOS------------------------------------------
CREATE TRIGGER TR_UPDATE_CLIENTE
ON CLIENTES
FOR UPDATE
AS
	DECLARE @CODIGO_CLIENTE INT;
	DECLARE @NOMBRE_DESPUES VARCHAR(50);
	DECLARE @FECHA_CREACION_DESPUES DATETIME;
	DECLARE @TELEFONO_DESPUES VARCHAR(10);
	DECLARE @CREDITO_DESPUES MONEY;
	DECLARE @TIPO_TRANSACCION VARCHAR(5) = 'UPD';
	SELECT @CODIGO_CLIENTE = CODIGO_CLIENTE FROM CLIENTES;
	SELECT @NOMBRE_DESPUES = NOMBRE_CLIENTE FROM CLIENTES;
	SELECT @FECHA_CREACION_DESPUES = FECHA_CREACION FROM CLIENTES;
	SELECT @TELEFONO_DESPUES = TELEFONO FROM CLIENTES;
	SELECT @CREDITO_DESPUES = CREDITO_MAXIMO FROM CLIENTES;
	
	UPDATE AUD_CLIENTES
	SET  NOMBRE_ANTES = NOMBRE_DESPUES, 
		 FECHA_CREACION_ANTES = FECHA_CREACION_DESPUES, 
		 TELEFONO_ANTES = TELEFONO_DESPUES,
		 CREDITO_ANTES = CREDITO_DESPUES,
		 NOMBRE_DESPUES = @NOMBRE_DESPUES,
		 FECHA_CREACION_DESPUES = @FECHA_CREACION_DESPUES,
		 TELEFONO_DESPUES = @TELEFONO_DESPUES,
		 CREDITO_DESPUES = @CREDITO_DESPUES,
		 MODIFICADO_POR = SYSTEM_USER, 
	   	 FECHA = GETDATE(),
		 TIPO_TRANSACCION = @TIPO_TRANSACCION
	WHERE @CODIGO_CLIENTE = CODIGO_CLIENTE;

GO


-----------------------------------------------------------PRESENTACIÓN DE LAS TABLAS--------------------------------------------------------
SELECT * FROM CLIENTES;
SELECT * FROM AUD_CLIENTES;


